### ISSUE TITLE
Integration tests are failing with master

### ISSUE THREAD

**Issue by lzap** [abenari/rbovirt#100]
Against oVirt 3.6:

```
 1) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
     Failure/Error: @client.vm_start_with_cloudinit(@vm.id, user_data)
     OVIRT::OvirtException:
       Cannot run VM because the VM is in Powering Down status.
     Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:128
     # ./lib/rbovirt.rb:202:in `handle_fault'
     # ./lib/rbovirt.rb:129:in `rescue in http_post'
     # ./lib/rbovirt.rb:124:in `http_post'
     # ./lib/client/vm_api.rb:150:in `vm_start_with_cloudinit'
     # ./spec/integration/vm_crud_spec.rb:47:in `block (2 levels) in <top (required)>'

  2) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
     Failure/Error: @client.vm_action(@vm.id, :start)
     OVIRT::OvirtException:
       Cannot run VM because the VM is in Powering Down status.
     Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:128
     # ./lib/rbovirt.rb:202:in `handle_fault'
     # ./lib/rbovirt.rb:129:in `rescue in http_post'
     # ./lib/rbovirt.rb:124:in `http_post'
     # ./lib/client/vm_api.rb:138:in `vm_action'
     # ./spec/integration/vm_crud_spec.rb:54:in `block (2 levels) in <top (required)>'

  3) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
     Failure/Error: @client.vm_start_with_cloudinit(@vm.id, user_data)
     OVIRT::OvirtException:
       Cannot run VM because the VM is in Powering Down status.
     Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:150
     # ./lib/rbovirt.rb:202:in `handle_fault'
     # ./lib/rbovirt.rb:129:in `rescue in http_post'
     # ./lib/rbovirt.rb:124:in `http_post'
     # ./lib/client/vm_api.rb:150:in `vm_start_with_cloudinit'
     # ./spec/integration/vm_crud_spec.rb:47:in `block (2 levels) in <top (required)>'

  4) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
     Failure/Error: @client.vm_action(@vm.id, :start)
     OVIRT::OvirtException:
       Cannot run VM because the VM is in Powering Down status.
     Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:150
     # ./lib/rbovirt.rb:202:in `handle_fault'
     # ./lib/rbovirt.rb:129:in `rescue in http_post'
     # ./lib/rbovirt.rb:124:in `http_post'
     # ./lib/client/vm_api.rb:138:in `vm_action'
     # ./spec/integration/vm_crud_spec.rb:54:in `block (2 levels) in <top (required)>'

  5) VM API support functions options processing should process template option into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'

  6) VM API support functions options processing should process template_name option into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'

  7) VM API support functions options processing should process template and storagedomain options into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'

  8) VM API support functions options processing should process template_name and storagedomain options into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'

  9) VM API support functions options processing should process template and storagedomain_name options into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'

  10) VM API support functions options processing should process template_name and storagedomain_name options into disk decriptions
     Failure/Error: @template_name = @config['template'] || @client.templates.first.name
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/integration/vm_crud_spec.rb:159:in `block (2 levels) in <top (required)>'
```

**Comment by lzap** [comment]
The issue is when you attempt to run tests on clean instance (just installed one). There are no templates created apparently, so this code fails to run:

```ruby
  before(:all) do
    setup_client

    @template_name = @config['template'] || @client.templates.first.name
    @template = @client.templates.find { |t| t.name == @template_name }.id
    @template_disks = @client.template_volumes(@template)
    @storagedomain = @client.storagedomains.first.id
    @storagedomain_name = @client.storagedomains.first.name
  end
```
