### ISSUE TITLE
Integration tests do not work on RHEL 6 against oVirt 3.5

### ISSUE THREAD

**Issue by lzap** [abenari/rbovirt#68]
Hello,

it looks like latest changes in the master broke the integration tests. Can you take a look please?

```
# ** Invoke spec (first_time)
# ** Execute spec
# /opt/rh/ruby193/root/usr/bin/ruby -S rspec ./spec/unit/client_spec.rb ./spec/unit/vm_spec.rb ./spec/integration/api_spec.rb ./spec/integration/vm_crud_spec.rb --color
# .............FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
# 
# Failures:
# 
#   1) OVIRT Https authentication authenticate using the server ca certificate should_authenticate_with_ca_certificate
#      Failure/Error: client.api_version.class.should eql(String)
#      OVIRT::OvirtException:
#        can't convert String into time interval
#      # ./lib/rbovirt.rb:195:in `handle_fault'
#      # ./lib/rbovirt.rb:112:in `rescue in http_get'
#      # ./lib/rbovirt.rb:107:in `http_get'
#      # ./lib/rbovirt.rb:79:in `api_version'
#      # ./spec/integration/api_spec.rb:56:in `block (3 levels) in <top (required)>'
# 
#   2) OVIRT Admin API basic admin api and listing test_should_return_hosts
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   3) OVIRT Admin API basic admin api and listing behaves like API test_should_return_a_version
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   4) OVIRT Admin API basic admin api and listing behaves like API test_should_return_datacenters
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   5) OVIRT Admin API basic admin api and listing behaves like API test_should_return_clusters
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   6) OVIRT Admin API basic admin api and listing behaves like API test_should_return_templates
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   7) OVIRT Admin API basic admin api and listing behaves like API test_should_return_vms
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   8) OVIRT Admin API basic admin api and listing behaves like API test_should_return_storage
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:71
#      # ./spec/integration/api_spec.rb:64:in `block (2 levels) in <top (required)>'
# 
#   9) OVIRT User API basic user api and listing test_should_not_return_hosts
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   10) OVIRT User API basic user api and listing behaves like API test_should_return_a_version
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   11) OVIRT User API basic user api and listing behaves like API test_should_return_datacenters
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   12) OVIRT User API basic user api and listing behaves like API test_should_return_clusters
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   13) OVIRT User API basic user api and listing behaves like API test_should_return_templates
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   14) OVIRT User API basic user api and listing behaves like API test_should_return_vms
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   15) OVIRT User API basic user api and listing behaves like API test_should_return_storage
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "API" called from ./spec/integration/api_spec.rb:90
#      # ./spec/integration/api_spec.rb:83:in `block (2 levels) in <top (required)>'
# 
#   16) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_create_template
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   17) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_template
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   18) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   19) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_start_and_stop_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   20) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   21) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   22) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_destroy_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   23) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_update_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   24) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_create_a_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   25) Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_update_volume
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:127
#      # ./spec/integration/vm_crud_spec.rb:123:in `block (2 levels) in <top (required)>'
# 
#   26) Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_return_a_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "VM Life cycle without template" called from ./spec/integration/vm_crud_spec.rb:138
#      # ./spec/integration/vm_crud_spec.rb:134:in `block (2 levels) in <top (required)>'
# 
#   27) Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_update_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "VM Life cycle without template" called from ./spec/integration/vm_crud_spec.rb:138
#      # ./spec/integration/vm_crud_spec.rb:134:in `block (2 levels) in <top (required)>'
# 
#   28) Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_start_and_stop_vm
#      Failure/Error: setup_client
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "VM Life cycle without template" called from ./spec/integration/vm_crud_spec.rb:138
#      # ./spec/integration/vm_crud_spec.rb:134:in `block (2 levels) in <top (required)>'
# 
#   29) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_create_template
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   30) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_template
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   31) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_vm
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   32) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_start_and_stop_vm
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   33) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   34) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   35) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_destroy_vm
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   36) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_update_vm
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   37) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_create_a_vm
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
#   38) User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_update_volume
#      Failure/Error: setup_client :filtered_api => support_user_level_api
#      RuntimeError:
#        Cannot find datacenter local_datacenter
#      Shared Example Group: "Basic VM Life cycle" called from ./spec/integration/vm_crud_spec.rb:149
#      # ./spec/integration/vm_crud_spec.rb:145:in `block (2 levels) in <top (required)>'
# 
# Finished in 0.388 seconds
# 51 examples, 38 failures
# 
# Failed examples:
# 
# rspec ./spec/integration/api_spec.rb:49 # OVIRT Https authentication authenticate using the server ca certificate should_authenticate_with_ca_certificate
# rspec ./spec/integration/api_spec.rb:73 # OVIRT Admin API basic admin api and listing test_should_return_hosts
# rspec ./spec/integration/api_spec.rb:16 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_a_version
# rspec ./spec/integration/api_spec.rb:20 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_datacenters
# rspec ./spec/integration/api_spec.rb:24 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_clusters
# rspec ./spec/integration/api_spec.rb:28 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_templates
# rspec ./spec/integration/api_spec.rb:32 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_vms
# rspec ./spec/integration/api_spec.rb:36 # OVIRT Admin API basic admin api and listing behaves like API test_should_return_storage
# rspec ./spec/integration/api_spec.rb:92 # OVIRT User API basic user api and listing test_should_not_return_hosts
# rspec ./spec/integration/api_spec.rb:16 # OVIRT User API basic user api and listing behaves like API test_should_return_a_version
# rspec ./spec/integration/api_spec.rb:20 # OVIRT User API basic user api and listing behaves like API test_should_return_datacenters
# rspec ./spec/integration/api_spec.rb:24 # OVIRT User API basic user api and listing behaves like API test_should_return_clusters
# rspec ./spec/integration/api_spec.rb:28 # OVIRT User API basic user api and listing behaves like API test_should_return_templates
# rspec ./spec/integration/api_spec.rb:32 # OVIRT User API basic user api and listing behaves like API test_should_return_vms
# rspec ./spec/integration/api_spec.rb:36 # OVIRT User API basic user api and listing behaves like API test_should_return_storage
# rspec ./spec/integration/vm_crud_spec.rb:20 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_create_template
# rspec ./spec/integration/vm_crud_spec.rb:29 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_template
# rspec ./spec/integration/vm_crud_spec.rb:33 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_vm
# rspec ./spec/integration/vm_crud_spec.rb:37 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_start_and_stop_vm
# rspec ./spec/integration/vm_crud_spec.rb:44 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
# rspec ./spec/integration/vm_crud_spec.rb:53 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
# rspec ./spec/integration/vm_crud_spec.rb:61 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_destroy_vm
# rspec ./spec/integration/vm_crud_spec.rb:67 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_update_vm
# rspec ./spec/integration/vm_crud_spec.rb:72 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_create_a_vm
# rspec ./spec/integration/vm_crud_spec.rb:79 # Admin API VM Life cycle admin basic vm and templates operations behaves like Basic VM Life cycle test_should_update_volume
# rspec ./spec/integration/vm_crud_spec.rb:103 # Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_return_a_vm
# rspec ./spec/integration/vm_crud_spec.rb:107 # Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_update_vm
# rspec ./spec/integration/vm_crud_spec.rb:112 # Admin API VM Life cycle without any template admin basic vm and templates operations behaves like VM Life cycle without template test_should_start_and_stop_vm
# rspec ./spec/integration/vm_crud_spec.rb:20 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_create_template
# rspec ./spec/integration/vm_crud_spec.rb:29 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_template
# rspec ./spec/integration/vm_crud_spec.rb:33 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_return_a_vm
# rspec ./spec/integration/vm_crud_spec.rb:37 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_start_and_stop_vm
# rspec ./spec/integration/vm_crud_spec.rb:44 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_start_with_cloudinit
# rspec ./spec/integration/vm_crud_spec.rb:53 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_set_vm_ticket
# rspec ./spec/integration/vm_crud_spec.rb:61 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_destroy_vm
# rspec ./spec/integration/vm_crud_spec.rb:67 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_update_vm
# rspec ./spec/integration/vm_crud_spec.rb:72 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_create_a_vm
# rspec ./spec/integration/vm_crud_spec.rb:79 # User API VM Life cycle user basic vm and templates operations behaves like Basic VM Life cycle test_should_update_volume
# rake aborted!
# /opt/rh/ruby193/root/usr/bin/ruby -S rspec ./spec/unit/client_spec.rb ./spec/unit/vm_spec.rb ./spec/integration/api_spec.rb ./spec/integration/vm_crud_spec.rb --color failed
# /opt/rh/ruby193/root/usr/share/gems/gems/rspec-core-2.11.1/lib/rspec/core/rake_task.rb:137:in `block (2 levels) in initialize'
# /opt/rh/ruby193/root/usr/share/ruby/rake/file_utils_ext.rb:60:in `verbose'
# /opt/rh/ruby193/root/usr/share/gems/gems/rspec-core-2.11.1/lib/rspec/core/rake_task.rb:127:in `block in initialize'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:205:in `call'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:205:in `block in execute'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `each'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `execute'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:158:in `block in invoke_with_call_chain'
# /opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:151:in `invoke_with_call_chain'
# /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:144:in `invoke'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:116:in `invoke_task'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block (2 levels) in top_level'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `each'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block in top_level'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:88:in `top_level'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:66:in `block in run'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
# /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:63:in `run'
# /opt/rh/ruby193/root/usr/bin/rake:32:in `<main>'
# Tasks: TOP => spec
```

My daily testing was broken for some time, but once I fix RHEL 6, I will start again testing against RHEL 7 too.

I get the same result against oVirt 3.4. Ping me if you want to see/clone beaker jobs I run every day.

**Comment by abenari** [comment]
@lzap hi,
I don't have ovirt installed at the moment, if you could fix the failing tests I'll be more than happy to merge the fix.
Thanks,
  Amos.

**Comment by lzap** [comment]
Let me take a look later on!
